# Generated by Django 5.2.2 on 2026-08-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0002_school_trainerprofile_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainerprofile",
            name="profile_photo",
        ),
    ]
