# Generated by Django 5.1.15 on 2026-08-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("timetable", "0001_initial"),
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.PositiveIntegerField()),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("students_present", models.IntegerField(default=0)),
                ("topic_taught", models.TextField()),
                ("activity", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="classes.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="classes.subject",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="timetable.timetable",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="trainers.trainerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "ordering": ["-date", "-start_time", "-session_number"],
                "indexes": [
                    models.Index(
                        fields=["trainer", "date"],
                        name="class_sessi_trainer_f4cd3a_idx",
                    ),
                    models.Index(
                        fields=["school_class", "subject"],
                        name="class_sessi_school__20f998_idx",
                    ),
                    models.Index(fields=["date"], name="class_sessi_date_672c70_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school_class", "subject", "session_number"),
                        name="unique_session_number_per_class_subject",
                    )
                ],
            },
        ),
    ]
