# Generated by Django 5.1.15 on 2026-08-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_sessions", "0002_session_period_session_school"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="unique_session_number_per_class_subject",
        ),
        migrations.AddField(
            model_name="session",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="session",
            name="students_absent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="total_students",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
