# Generated by Django 5.1.15 on 2026-08-19 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        ("trainers", "0002_school_trainerprofile_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="period",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="trainers.school",
            ),
        ),
    ]
