# Generated by Django 5.1.15 on 2026-08-19 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("timetable", "0001_initial"),
        ("trainers", "0002_school_trainerprofile_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("period", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date", "period", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimetableOccurrenceRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AlterModelOptions(
            name="timetable",
            options={"ordering": ["day_of_week", "period", "start_time"]},
        ),
        migrations.AddField(
            model_name="timetable",
            name="period",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetable",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable",
                to="trainers.school",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="source",
            field=models.CharField(
                choices=[("EXCEL", "Excel Upload"), ("MANUAL", "Manual")],
                default="MANUAL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable",
                to="classes.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["trainer", "school", "is_active"],
                name="timetable_t_trainer_8333d1_idx",
            ),
        ),
        migrations.AddField(
            model_name="manualclass",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_classes",
                to="trainers.school",
            ),
        ),
        migrations.AddField(
            model_name="manualclass",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_classes",
                to="classes.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="manualclass",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_classes",
                to="classes.subject",
            ),
        ),
        migrations.AddField(
            model_name="manualclass",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_classes",
                to="trainers.trainerprofile",
            ),
        ),
        migrations.AddField(
            model_name="timetableoccurrenceremoval",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrence_removals",
                to="timetable.timetable",
            ),
        ),
        migrations.AddIndex(
            model_name="manualclass",
            index=models.Index(
                fields=["trainer", "date"], name="timetable_m_trainer_1eb262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manualclass",
            index=models.Index(
                fields=["trainer", "school"], name="timetable_m_trainer_e4ab73_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableoccurrenceremoval",
            constraint=models.UniqueConstraint(
                fields=("timetable", "date"),
                name="unique_occurrence_removal_per_timetable_date",
            ),
        ),
    ]
