# Generated by Django 5.1.15 on 2026-08-26 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_manualclass_timetableoccurrenceremoval_and_more"),
        ("trainers", "0003_remove_trainerprofile_profile_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HOLIDAY", "Holiday"),
                            ("CLASS_REMOVED", "Class Removed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedule_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="trainers.school",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="timetable.timetable",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="trainers.trainerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["trainer", "date"],
                        name="timetable_s_trainer_0a0443_idx",
                    ),
                    models.Index(
                        fields=["date", "type"], name="timetable_s_date_43e197_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trainer", "date", "type"),
                        name="unique_holiday_per_trainer_date",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("type", "CLASS_REMOVED")),
                        fields=("timetable", "date", "type"),
                        name="unique_class_removal_per_timetable_date",
                    ),
                ],
            },
        ),
    ]
